<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="Me-Pc" name="com.maven.testng1.BTest1" tests="11" failures="0" timestamp="07 Dec 2018 10:01:20 GMT" time="5.045" errors="1">
  <testcase name="bTest3" time="0.001" classname="com.maven.testng1.BTest1"/>
  <testcase name="bTest3" time="0.005" classname="com.maven.testng1.BTest1"/>
  <testcase name="bTest3" time="0.002" classname="com.maven.testng1.BTest1"/>
  <testcase name="bTest3" time="0.001" classname="com.maven.testng1.BTest1"/>
  <testcase name="bTest3" time="0.001" classname="com.maven.testng1.BTest1"/>
  <testcase name="bTest3" time="0.001" classname="com.maven.testng1.BTest1"/>
  <testcase name="bTest3" time="0.001" classname="com.maven.testng1.BTest1"/>
  <testcase name="bTest4" time="0.004" classname="com.maven.testng1.BTest1"/>
  <testcase name="bTest3" time="0.002" classname="com.maven.testng1.BTest1"/>
  <testcase name="bTest2" time="5.027" classname="com.maven.testng1.BTest1">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.maven.testng1.BTest1.bTest2() didn&#039;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.maven.testng1.BTest1.bTest2() didn't finish within the time-out 5000at java.lang.ThreadGroup.remove(Unknown Source)at java.lang.ThreadGroup.threadTerminated(Unknown Source)at java.lang.Thread.exit(Unknown Source)]]>
    </error>
  </testcase> <!-- bTest2 -->
  <testcase name="bTest1" classname="com.maven.testng1.BTest1">
    <skipped/>
  </testcase> <!-- bTest1 -->
</testsuite> <!-- com.maven.testng1.BTest1 -->
